### ISSUE TITLE
docker image: support ARM architectures

### ISSUE THREAD

**Issue by abualy** [domeneshop/cert-manager-webhook-domeneshop#2]
Hi,
It would be awesome to support arm based architectures for the docker image used  in the helm chart.
l run a k8s cluster on raspberry PI cluster, and use v8 arm based Raspberry Pi OS as an OS, and so the image doesnt work for my setup

**Comment by jonasbartho** [comment]
The same problem still occurs on ARM based architectures(k3s-cluster on raspberry PI in my case)...

**Comment by abualy** [comment]
i moved to managing my domain on cloudflare, and using certmanager auto renewal there, never looked back!
https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/

**Comment by eirikrye** [comment]
Hello,

Apologies for taking so long with this. Multi-arch images have now been built and pushed to Docker Hub.
