### ISSUE TITLE
Certificate issuing fails

### ISSUE THREAD

**Issue by bernhardfrenking** [domeneshop/cert-manager-webhook-domeneshop#4]
Hello domeneshop developer and users,

could someone help me to debug, I tried to get a certificate, but it fails with (test.example.com ist ersetzt):

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"name":"test-certificate","namespace":"default"},"spec":{"dnsNames":["test.example.com"],"issuerRef":{"kind":"Issuer","name":"domeneshop-dns01"},"secretName":"test-secret-tls"}}
  creationTimestamp: "2022-10-29T14:52:58Z"
  generation: 1
  name: test-certificate
  namespace: default
  resourceVersion: "4292474"
  uid: 3b52a1af-481a-468e-a4c4-87a0d2e0af6f
spec:
  dnsNames:
  - test.example.com
  issuerRef:
    kind: Issuer
    name: domeneshop-dns01
  secretName: test-secret-tls
status:
  conditions:
  - lastTransitionTime: "2022-10-29T14:52:58Z"
    message: Issuing certificate as Secret does not exist
    observedGeneration: 1
    reason: DoesNotExist
    status: "True"
    type: Issuing
  - lastTransitionTime: "2022-10-29T14:52:58Z"
    message: Issuing certificate as Secret does not exist
    observedGeneration: 1
    reason: DoesNotExist
    status: "False"
    type: Ready
  nextPrivateKeySecretName: test-certificate-m4gsr
```

I'm using cert-manager v1.10.0 and I followed the README of this repo.

I'm happy about any hint, that could help me :-)

Thx a lot

**Comment by eirikrye** [comment]
Hello,

You haven't really provided much information.

Check the output of `kubectl describe orders.acme.cert-manager.io test-certificate` and `kubectl describe orders.acme.cert-manager.io test-certificate` to see if it fails during issuance. You can also check `kubectl get events` to see recent events.

Also, check the logs of the `cert-manager` pod, e.g. `kubectl logs -n cert-manager cert-manager-<id>`

**Comment by bernhardfrenking** [comment]
Thx for the fast response :-)
The first  command looks ok for me:
`
kubectl describe orders.acme.cert-manager.io test-certificate

Name:         test-certificate-hqqz7-266096095
Namespace:    default
Labels:       <none>
Annotations:  cert-manager.io/certificate-name: test-certificate
              cert-manager.io/certificate-revision: 1
              cert-manager.io/private-key-secret-name: test-certificate-m4gsr
API Version:  acme.cert-manager.io/v1
Kind:         Order
Metadata:
  Creation Timestamp:  2022-10-29T14:52:58Z
  Generation:          1
  Managed Fields:
    API Version:  acme.cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:cert-manager.io/certificate-name:
          f:cert-manager.io/certificate-revision:
          f:cert-manager.io/private-key-secret-name:
        f:ownerReferences:
          .:
          k:{"uid":"2dc0a4ff-9e59-4f23-9ad2-b49083b548f9"}:
      f:spec:
        .:
        f:dnsNames:
        f:issuerRef:
          .:
          f:kind:
          f:name:
        f:request:
    Manager:      cert-manager-certificaterequests-issuer-acme
    Operation:    Update
    Time:         2022-10-29T14:52:58Z
    API Version:  acme.cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:authorizations:
        f:finalizeURL:
        f:state:
        f:url:
    Manager:      cert-manager-orders
    Operation:    Update
    Subresource:  status
    Time:         2022-10-29T14:53:00Z
  Owner References:
    API Version:           cert-manager.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  CertificateRequest
    Name:                  test-certificate-hqqz7
    UID:                   2dc0a4ff-9e59-4f23-9ad2-b49083b548f9
  Resource Version:        4292486
  UID:                     6d066fb0-7dbc-4e9e-80bb-53dcc289c8d6
Spec:
  Dns Names:
    test.example.com
  Issuer Ref:
    Kind:   Issuer
    Name:   domeneshop-dns01
  Request:  <request>
Status:
  Authorizations:
    Challenges:
      Token:        <token>
      Type:         http-01
      URL:          https://acme-v02.api.letsencrypt.org/acme/chall-v3/170069076642/3uOMnA
      Token:        <token>
      Type:         dns-01
      URL:          https://acme-v02.api.letsencrypt.org/acme/chall-v3/170069076642/pvCK0w
      Token:        <token>
      Type:         tls-alpn-01
      URL:          https://acme-v02.api.letsencrypt.org/acme/chall-v3/170069076642/Hxl3wQ
    Identifier:     test.example.com
    Initial State:  pending
    URL:            https://acme-v02.api.letsencrypt.org/acme/authz-v3/170069076642
    Wildcard:       false
  Finalize URL:     https://acme-v02.api.letsencrypt.org/acme/finalize/800123072/139059782252
  State:            pending
  URL:              https://acme-v02.api.letsencrypt.org/acme/order/800123072/139059782252
Events:             <none>`

The logs of the cert-manager logs suspicious:
`cert-manager/challenges "msg"="re-queuing item due to error processing" "error"="secrets \"domeneshop-credentials\" is forbidden: User \"system:serviceaccount:webhook-domeneshop:webhook-cert-manager-webhook-domeneshop\" cannot get resource \"secrets\" in API group \"\" in the namespace \"default\"" "key"="default/test-certificate-7qnn6-266096095-2073264634"`
But I don't get it. It looks like the secret can not be accessed.
The Issuer and the Certificate is created in default - but this as I see it also like in the README.

The secret is created with 
`kubectl create secret generic domeneshop-credentials \
    --namespace webhook-domeneshop \
    --from-literal=APIToken=<base64 encoded> \
    --from-literal=APISecret=<base64 encoded>`

Could you help me out how to solve it? Thx :-)

**Comment by eirikrye** [comment]
You'd have to create a Role+RoleBinding to let the webhook Service Account `system:serviceaccount:webhook-domeneshop:webhook-cert-manager-webhook-domeneshop` read the secret in the default namespace.

**Comment by bernhardfrenking** [comment]
Thx, that did the job (-:
